### ISSUE TITLE
JABS won't display names of files opened in buffers if they were not previously focused

### ISSUE THREAD

**Issue by SenchoPens** [matbme/JABS.nvim#11] opened 2021-08-07 20:48 UTC
Hi!
For example: after executing `nvim init.vim init.lua` and calling `:JABSOpen` I see the following:
![image](https://user-images.githubusercontent.com/20418252/128613483-3194152d-a0cb-4026-81b7-fb3a68898ca8.png)
Then, if I select the `init.lua` buffer, JABS is working fine and displaying all filenames.
I use the latest JABS.

**Comment by matbme** [comment] 2021-08-08 22:47
Hello!

Just pushed a [commit](https://github.com/matbme/JABS.nvim/commit/d1d708f0d5c5ab569f7d092723ca70ca7fcf2fa4) to the `bugfix` branch that should fix the issue. Could you configure your plugin manager to pull from that branch and test it out?

**Comment by matbme** [comment] 2021-08-13 11:26
I did some testing and I could not reproduce the issue anymore, so I merged bugfix into main. If you still have problems, please reopen the issue :)

**Closed by matbme** 2021-08-13 11:26 UTC

**Comment by SenchoPens** [comment] 2021-08-13 13:56
Hi! Sorry that I did not reply to your first comment. Everything is working perfectly now, thanks!
